name: Download SharePoint JSON File

on:
  workflow_dispatch:

jobs:
  download-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install PnP PowerShell
        run: pwsh -Command "Install-Module PnP.PowerShell -AllowClobber -Force"

      - name: Decode Certificate from Base64
        env:
          CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
        run: |
          pwsh -Command "
          Write-Host 'Starting the decoding process...'
          $base64 = '${{ env.CERTIFICATE_BASE64 }}'
          Write-Host 'Base64 string length: ' + $base64.Length
          $certPassword = ConvertTo-SecureString -String '${{ env.CERTIFICATE_PASSWORD }}' -AsPlainText -Force
          $certBytes = [System.Convert]::FromBase64String('$base64')
          Write-Host 'Number of bytes decoded: ' + $certBytes.Length
          $certPath = 'certificate.pfx'
          [System.IO.File]::WriteAllBytes($certPath, $certBytes)
          Write-Host 'Certificate written to $certPath'"


      - name: Download JSON file from SharePoint
        run: |
          pwsh -Command "
          $tenantId = '${{ secrets.TENANT_ID }}'
          $appId = '${{ secrets.CLIENT_ID }}'
          $siteUrl = 'https://coopernorman.sharepoint.com/sites/CN-DataInformation'
          $jsonFilePath = '/Shared Documents/other/profile-picture-blob.json'
          $localPath = 'profile-pictures' # Path in the GitHub runner
          $jsonFileName = 'profile-picture-blob.json' # Name of the file

          $certPath = 'certificate.pfx'
          $certPassword = ConvertTo-SecureString -String '${{ env.CERTIFICATE_PASSWORD }}' -AsPlainText -Force
          $certificate = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2($certPath, $certPassword)

          Connect-PnPOnline -Url $siteUrl -ClientId $appId -Tenant $tenantId -Certificate $certificate
          Get-PnPFile -ServerRelativeUrl $jsonFilePath -Path $localPath -FileName $jsonFileName -AsFile
          Disconnect-PnPOnline"

      - name: Commit and Push File to Repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add profile-pictures
          git commit -m "Add downloaded JSON file"
          git push
