name: Upload Profile Pictures from SharePoint

on:
  workflow_dispatch:
    inputs:
      images_json:
        description: 'JSON array of image URLs and filenames from SharePoint'
        required: true

jobs:
  upload-images:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Download and Save Images
        run: |
          mkdir -p profile_pictures
          echo '${{ github.event.inputs.images_json }}' | jq -c '.[]' | while read i; do
            img_url=$(echo $i | jq -r '.image_url')
            img_name=$(echo $i | jq -r '.image_name')
            curl -L $img_url -o ./profile_pictures/$img_name
          done

      - name: Commit and Push Images to Repository
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./profile_pictures
          git commit -m "Batch upload of profile pictures from SharePoint"
          git remote set-url origin https://x-access-token:${ACCESS_TOKEN}@github.com/CNHubData/assets.git
          git push origin main
