name: Upload Profile Pictures

on:
  workflow_dispatch:
    inputs:
      image_data:
        description: 'Base64 encoded image data'
        required: true
      image_name:
        description: 'Name of the image file'
        required: true

jobs:
  upload-images:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Decode and Save Image
        run: |
          mkdir -p profile_pictures
          echo "${{ github.event.inputs.image_data }}" | base64 --decode > ./profile_pictures/${{ github.event.inputs.image_name }}

      - name: Commit and Push Image to Repository
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git add ./profile_pictures
          git commit -m "Upload new profile picture"
          git remote set-url origin https://x-access-token:${ACCESS_TOKEN}@github.com/CNHubData/assets.git
          git fetch
          git reset --soft origin/main
          git push --force-with-lease origin main
