name: Batch Upload Profile Pictures from SharePoint

on:
  workflow_dispatch:
    inputs:
      json_url:
        description: 'URL of the JSON file on SharePoint'
        required: true

jobs:
  download-and-process-images:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get OAuth Token
        id: get_token
        run: |
          response=$(curl -X POST -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=client_credentials&client_id=${{ secrets.CLIENT_ID }}&client_secret=${{ secrets.CLIENT_SECRET }}&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default" \
            "https://login.microsoftonline.com/${{ secrets.TENANT_ID }}/oauth2/v2.0/token")
          echo "::set-output name=token::$(echo $response | jq -r '.access_token')"

      - name: Fetch JSON from SharePoint
        run: |
          curl -v -H "Authorization: Bearer ${{ steps.get_token.outputs.token }}" "${{ github.event.inputs.json_url }}" -L -o images.json


      - name: Install jq for JSON parsing
        run: sudo apt-get install jq

      - name: Process JSON and Download Images
        run: |
          jq -c '.[]' images.json | while read i; do
            img_url=$(echo $i | jq -r '.image_url')
            img_name=$(echo $i | jq -r '.image_name')
            curl -L $img_url -o "./profile_pictures/$img_name"
          done

      - name: Commit and Push Images to Repository
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./profile_pictures
          git commit -m "Batch upload of profile pictures from SharePoint"
          git remote set-url origin https://x-access-token:${ACCESS_TOKEN}@github.com/CNHubData/assets.git
          git push origin main
