name: Process and Upload Images from JSON

on:
  workflow_dispatch:

jobs:
  process-and-upload-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Prepare Certificate
        run: |
          echo ${{ secrets.PFX_CERTIFICATE }} | base64 -d > ./certificate.pfx

      - name: Install PnP PowerShell
        run: pwsh -Command "Install-Module PnP.PowerShell -AllowClobber -Force"

      - name: Download JSON file from SharePoint
        shell: pwsh
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          CERTIFICATE_PATH: ./certificate.pfx
        run: |
          $tenantId = $env:TENANT_ID
          $appId = $env:CLIENT_ID
          $siteUrl = 'https://coopernorman.sharepoint.com/sites/CN-DataInformation'
          $jsonFilePath = '/Shared Documents/other/profile-picture-blob.json'
          $localPath = 'profile-pictures' # Path in the GitHub runner
          $jsonFileName = 'profile-picture-blob.json' # Name of the file

          # Ensure the directory exists
          if (-not (Test-Path -Path $localPath)) {
              New-Item -ItemType Directory -Path $localPath -Force
          }

          $certificatePath = "$PWD/certificate.pfx"
          $secureCertificatePassword = ConvertTo-SecureString -String $env:CERTIFICATE_PASSWORD -AsPlainText -Force
          $certificate = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2($certificatePath, $secureCertificatePassword)

          Connect-PnPOnline -Url $siteUrl -ClientId $appId -Tenant $tenantId -CertificatePath $certificatePath -CertificatePassword $secureCertificatePassword
          Get-PnPFile -ServerRelativeUrl $jsonFilePath -Path $localPath -FileName $jsonFileName -AsFile -Force
          Disconnect-PnPOnline

      - name: Process JSON and Save Images
        shell: pwsh
        run: |
          $jsonFile = "profile-pictures/profile-picture-blob.json"
          $jsonContent = Get-Content -Path $jsonFile -Raw | ConvertFrom-Json
          foreach ($entry in $jsonContent) {
              $imageData = $entry.inputs.image_data
              $imageName = $entry.inputs.image_name
              $imagePath = "profile-pictures/$imageName"
              $imageDataBytes = [System.Convert]::FromBase64String($imageData)
              [System.IO.File]::WriteAllBytes($imagePath, $imageDataBytes)
          }

      - name: Commit and Push Images to Repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add profile-pictures/*.jpg
          git add profile-pictures/profile-picture-blob.json
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Add processed images from JSON"
            git push
          else
            echo "No changes to commit"
          fi
