name: Download and Process Images from SharePoint JSON

on:
  workflow_dispatch:

jobs:
  download-and-process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up PowerShell
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '3.1.x'  # Specify a .NET version that includes PowerShell

      - name: Prepare Certificate
        run: |
          echo ${{ secrets.PFX_CERTIFICATE }} | base64 -d > ./certificate.pfx

      - name: Install PnP PowerShell
        run: pwsh -Command "Install-Module PnP.PowerShell -AllowClobber -Force"

      - name: Download JSON file from SharePoint
        shell: pwsh
        env:
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
        run: |
          $tenantId = 'a37996c3-3856-4ede-9812-4bbd17884862'
          $appId = 'd7bcacec-6088-406d-a61a-e0d61f30c2d7'
          $siteUrl = 'https://coopernorman.sharepoint.com/sites/CN-DataInformation'
          $jsonFilePath = '/Shared Documents/other/profile-picture-blob.json'
          $localPath = 'profile-pictures' # Path in the GitHub runner
          $jsonFileName = 'profile-picture-blob.json' # Name of the file

          # Ensure the directory exists
          if (-not (Test-Path -Path $localPath)) {
              New-Item -ItemType Directory -Path $localPath -Force
          }

          $certificatePath = "$PWD/certificate.pfx"
          $secureCertificatePassword = ConvertTo-SecureString -String $env:CERTIFICATE_PASSWORD -AsPlainText -Force
          $certificate = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2($certificatePath, $secureCertificatePassword)

          Connect-PnPOnline -Url $siteUrl -ClientId $appId -Tenant $tenantId -CertificatePath $certificatePath -CertificatePassword $secureCertificatePassword
          Get-PnPFile -ServerRelativeUrl $jsonFilePath -Path $localPath -FileName $jsonFileName -AsFile
          Disconnect-PnPOnline

      - name: Process JSON and Extract Images
        shell: pwsh
        run: |
          $localPath = 'profile-pictures'
          $jsonFilePath = "$localPath/profile-picture-blob.json"

          $jsonContent = Get-Content -Path $jsonFilePath -Raw | ConvertFrom-Json
          foreach ($item in $jsonContent) {
              $imageName = $item.image_name
              $imageData = $item.image_data
              $imageBytes = [System.Convert]::FromBase64String($imageData)
              $imagePath = Join-Path -Path $localPath -ChildPath $imageName
              [System.IO.File]::WriteAllBytes($imagePath, $imageBytes)
          }

      - name: Commit and Push Images to Repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add profile-pictures
          git commit -m "Add extracted images from JSON"
          git push
